### PR TITLE
Migration and Appconfig

### PR DESCRIPTION
**Pull request by marianoeramirez**

### CODE REVIEW

**Review by vly-ginger — APPROVED** [review]

**Comment by vly-ginger** [comment]
@marianoeramirez @FrankSalad is this safe to merge?

**Comment by FrankSalad** [comment]
@vly-ginger I think so, intent of this is to bring `master` back to the point that ginger-web requirements was pointing at.

**Comment by vly-ginger** [comment]
I tested this from local Docker (and also CI on develop). Once this is in and ginger-web's requirements.txt is updated to point to the final SHA, it will unblock the CI (build and unit tests). 

What I'm not certain of is if this change is **OK for Cigna** that the unit tests may not cover 100%.

**Comment by marianoeramirez** [comment]
Yes right, If you approve it, we can merge

**Comment by marianoeramirez** [comment]
Actually, Until i Know Cigna not use this code. or the ListenerAPIAuthentication. That is the place were I saw that we use this code

**Pull request merged**
